import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { toast } from 'sonner';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Form, FormControl, FormDescription, FormField, FormItem, FormMessage } from '@/components/ui/form';
import { Checkbox } from '@/components/ui/checkbox';
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { ArrowDown, ArrowUp, Circle, Copy, PackagePlus, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { useDebounce } from '@/hooks/use-debounce';
import InventoryService from '@/services/InventoryService';
import ProductionService from '@/services/ProductionService';
import { SemiFinishedProduct } from '@/services/InventoryService';
import { FinishedProduct } from '@/services/InventoryService';

const formSchema = z.object({
  product: z.string().min(2, {
    message: 'الرجاء اختيار منتج.',
  }),
  quantity: z.number().min(1, {
    message: 'الرجاء إدخال كمية صحيحة.',
  }),
});

const ProductionSimulation = () => {
  const [products, setProducts] = useState<SemiFinishedProduct[]>([]);
  const [finishedProducts, setFinishedProducts] = useState<FinishedProduct[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<SemiFinishedProduct | null>(null);
  const [quantity, setQuantity] = useState<number>(1);
  const [ingredients, setIngredients] = useState<{
    code: string;
    name: string;
    requiredQuantity: number;
    available: boolean;
    unit: string;
    cost: number;
  }[]>([]);
  const [packagingMaterials, setPackagingMaterials] = useState<{
    code: string;
    name: string;
    requiredQuantity: number;
    available: boolean;
    unit: string;
    cost: number;
  }[]>([]);
  const [totalCost, setTotalCost] = useState<number>(0);
  const [searchTerm, setSearchTerm] = useState<string>('');
  const debouncedSearchTerm = useDebounce(searchTerm, 500);
  const [isIngredientCostManually, setIsIngredientCostManually] = useState<boolean>(false);
  const [isPackagingCostManually, setIsPackagingCostManually] = useState<boolean>(false);
  const [ingredientManualCost, setIngredientManualCost] = useState<number>(0);
  const [packagingManualCost, setPackagingManualCost] = useState<number>(0);
  const [isFinishedProduct, setIsFinishedProduct] = useState<boolean>(false);
  const [isSemiFinishedProduct, setIsSemiFinishedProduct] = useState<boolean>(false);
  const [isSimulationRunning, setIsSimulationRunning] = useState<boolean>(false);
  const [isSimulationFinished, setIsSimulationFinished] = useState<boolean>(false);
  const [isSimulationFailed, setIsSimulationFailed] = useState<boolean>(false);
  const [simulationErrorMessage, setSimulationErrorMessage] = useState<string>('');
  const [isCreatingOrder, setIsCreatingOrder] = useState<boolean>(false);
  const [isResetting, setIsResetting] = useState<boolean>(false);
  const [isCopying, setIsCopying] = useState<boolean>(false);
  const [isDeleting, setIsDeleting] = useState<boolean>(false);
  const [isAddingPackaging, setIsAddingPackaging] = useState<boolean>(false);
  const [isAddingIngredient, setIsAddingIngredient] = useState<boolean>(false);
  const [isUpdatingIngredient, setIsUpdatingIngredient] = useState<boolean>(false);
  const [isUpdatingPackaging, setIsUpdatingPackaging] = useState<boolean>(false);
  const [isIngredientAvailable, setIsIngredientAvailable] = useState<boolean>(false);
  const [isPackagingAvailable, setIsPackagingAvailable] = useState<boolean>(false);
  const [isIngredientCostValid, setIsIngredientCostValid] = useState<boolean>(false);
  const [isPackagingCostValid, setIsPackagingCostValid] = useState<boolean>(false);
  const [isIngredientQuantityValid, setIsIngredientQuantityValid] = useState<boolean>(false);
  const [isPackagingQuantityValid, setIsPackagingQuantityValid] = useState<boolean>(false);
  const [isIngredientNameValid, setIsIngredientNameValid] = useState<boolean>(false);
  const [isPackagingNameValid, setIsPackagingNameValid] = useState<boolean>(false);
  const [isIngredientCodeValid, setIsIngredientCodeValid] = useState<boolean>(false);
  const [isPackagingCodeValid, setIsPackagingCodeValid] = useState<boolean>(false);
  const [isIngredientUnitValid, setIsIngredientUnitValid] = useState<boolean>(false);
  const [isPackagingUnitValid, setIsPackagingUnitValid] = useState<boolean>(false);
  const [isIngredientPercentageValid, setIsIngredientPercentageValid] = useState<boolean>(false);
  const [isPackagingPercentageValid, setIsPackagingPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageValid, setIsIngredientCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageValid, setIsPackagingCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostQuantityValid, setIsIngredientCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostQuantityValid, setIsPackagingCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostNameValid, setIsIngredientCostNameValid] = useState<boolean>(false);
  const [isPackagingCostNameValid, setIsPackagingCostNameValid] = useState<boolean>(false);
  const [isIngredientCostCodeValid, setIsIngredientCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostCodeValid, setIsPackagingCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostUnitValid, setIsIngredientCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostUnitValid, setIsPackagingCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostValid, setIsIngredientCostPercentageCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostValid, setIsPackagingCostPercentageCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageQuantityValid, setIsIngredientCostPercentageQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageQuantityValid, setIsPackagingCostPercentageQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageNameValid, setIsIngredientCostPercentageNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageNameValid, setIsPackagingCostPercentageNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCodeValid, setIsIngredientCostPercentageCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCodeValid, setIsPackagingCostPercentageCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageUnitValid, setIsIngredientCostPercentageUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageUnitValid, setIsPackagingCostPercentageUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentagePercentageValid, setIsIngredientCostPercentagePercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentagePercentageValid, setIsPackagingCostPercentagePercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostPercentageValid, setIsIngredientCostPercentageCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostPercentageValid, setIsPackagingCostPercentageCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostQuantityValid, setIsIngredientCostPercentageCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostQuantityValid, setIsPackagingCostPercentageCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostNameValid, setIsIngredientCostPercentageCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostNameValid, setIsPackagingCostPercentageCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCodeValid, setIsIngredientCostPercentageCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCodeValid, setIsPackagingCostPercentageCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostUnitValid, setIsIngredientCostPercentageCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostUnitValid, setIsPackagingCostPercentageCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostPercentageValid, setIsIngredientCostPercentageCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostPercentageValid, setIsPackagingCostPercentageCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostValid, setIsIngredientCostPercentageCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostValid, setIsPackagingCostPercentageCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostQuantityValid, setIsIngredientCostPercentageCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostQuantityValid, setIsPackagingCostPercentageCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostNameValid, setIsIngredientCostPercentageCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostNameValid, setIsPackagingCostPercentageCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCodeValid, setIsIngredientCostPercentageCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCodeValid, setIsPackagingCostPercentageCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostUnitValid, setIsIngredientCostPercentageCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostUnitValid, setIsPackagingCostPercentageCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostPercentageValid, setIsIngredientCostPercentageCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostPercentageValid, setIsPackagingCostPercentageCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostValid, setIsIngredientCostPercentageCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostValid, setIsPackagingCostPercentageCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCodeValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCodeValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCodeValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostUnitValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostUnitValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostUnitValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostPercentageValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid, setIsPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostQuantityValid] = useState<boolean>(false);
  const [isIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsIngredientCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid] = useState<boolean>(false);
  const [isPackagingCostPercentageCostCostCostCostCostCostCostCostCostCostCostCostCostCostNameValid, setIsPackagingCostPercentageCost
