// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmtzeqwyybgcjmkqhshr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdHplcXd5eWJnY2pta3Foc2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzkzOTksImV4cCI6MjA1ODI1NTM5OX0.USzf9MqbkRC9TAkuIbTjnjEZlRtRQMfDt4EPbi3aYXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for low stock queries - now using the database function
export const lowStockQueries = {
  rawMaterials() {
    // استخدام وظيفة الاستعلامات المحسنة
    return supabase
      .from('raw_materials')
      .select('id, name, quantity, min_stock, code, unit, unit_cost, importance')
      .lt('quantity', 'min_stock')
      .gt('min_stock', 0);
  },
  
  semiFinishedProducts() {
    return supabase
      .from('semi_finished_products')
      .select('id, name, quantity, min_stock, code, unit, unit_cost')
      .lt('quantity', 'min_stock')
      .gt('min_stock', 0);
  },
  
  packagingMaterials() {
    return supabase
      .from('packaging_materials')
      .select('id, name, quantity, min_stock, code, unit, unit_cost, importance')
      .lt('quantity', 'min_stock')
      .gt('min_stock', 0);
  },
  
  finishedProducts() {
    return supabase
      .from('finished_products')
      .select('id, name, quantity, min_stock, code, unit, unit_cost')
      .lt('quantity', 'min_stock')
      .gt('min_stock', 0);
  },

  // استعلام موحد باستخدام الوظيفة الجديدة 
  getAllLowStockItems() {
    return supabase.rpc('get_all_low_stock_items');
  }
};

// Create a modified supabase client for low stock queries
export const createLowStockFilter = (columnName: string) => {
  return `${columnName}.lt.min_stock`;
};

// Define custom RPC function types to workaround type issues
export const rpcFunctions = {
  async getProductionStats() {
    return await supabase.functions.invoke('get_production_stats') as unknown as { 
      data: { 
        total_production_orders: number;
        completed_orders: number;
        pending_orders: number;
        total_cost: number;
      } | null;
      error: any;
    };
  },
  
  async getMonthlyProductionStats() {
    return await supabase.functions.invoke('get_monthly_production_stats') as unknown as {
      data: { 
        month: string;
        production_count: number;
        packaging_count: number;
      }[] | null;
      error: any;
    };
  },
  
  // استخدام وظيفة جديدة للحصول على حركات المخزون
  async getInventoryMovementsByItem(itemId: string, itemType: string) {
    return await supabase.rpc('get_inventory_movements_by_item', {
      p_item_id: itemId,
      p_item_type: itemType
    });
  },

  // Helper function to replace coalesce_numeric RPC calls
  coalesceNumeric(column: string) {
    // This is a client-side helper method for querying columns when comparing to other columns
    // Used to replace the coalesce_numeric RPC calls
    return column;
  },
  
  // System functions for factory reset and backup/restore
  async factoryReset() {
    return await supabase.functions.invoke('factory-reset');
  },
  
  async createBackup() {
    return await supabase.functions.invoke('create-backup');
  },
  
  async restoreBackup(backupData: string) {
    return await supabase.functions.invoke('restore-backup', {
      body: { backup: backupData }
    });
  },

  // وظائف تحليلات المخزون المخصصة
  async getInventoryUsageDistribution(itemId: string, itemType: string, period: string) {
    return await supabase.rpc('get_inventory_usage_distribution', {
      p_item_id: itemId,
      p_item_type: itemType,
      p_period: period
    });
  },

  async getInventoryVolatility(itemId: string, itemType: string, period: string, periodsCount: number = 6) {
    return await supabase.rpc('get_inventory_volatility', {
      p_item_id: itemId,
      p_item_type: itemType,
      p_period: period,
      p_periods_count: periodsCount
    });
  },

  async getMostActiveInventoryItems(limit: number = 10, period: string = 'month') {
    return await supabase.rpc('get_most_active_inventory_items', {
      p_limit: limit,
      p_period: period
    });
  },

  async getInventoryMovementsByTime(itemId: string, itemType: string, period: string) {
    return await supabase.rpc('get_inventory_movements_by_time', {
      p_item_id: itemId,
      p_item_type: itemType,
      p_period: period
    });
  },

  async getInventorySummaryStats(itemId: string, itemType: string) {
    return await supabase.rpc('get_inventory_summary_stats', {
      p_item_id: itemId,
      p_item_type: itemType
    });
  }
};
